### PR TITLE
build: functional call from frontend to backend express server

### PR DESCRIPTION
**Pull request by alanhwu**
React frontend makes an API call to the backend express server to receive text

### CODE REVIEW

**Comment by jc-tung** [comment]
LGTM. Great work Alan and Nareth! Let's keep scrumming team!

**Review by steveez123 — APPROVED** [review]
nice

**Review by nareha — APPROVED** [review]
lgtm 🚢

**Review by jc-tung — APPROVED** [review]

**Comment by yl16961** [comment]
lgtm <3

**Pull request merged**
