### PR TITLE
feat: setup CI/CD

### LINKED ISSUE #41: Set up CI/CD with Github Actions

### PR DESCRIPTION
**Pull request by jc-tung**
Closes #41

### CODE REVIEW

**Review by nareha — COMMENTED** [review]
Sorry for this bit of nitpick-y code format request: could you add an empty line at the end of the files?

**Comment by nareha** [comment]
Also, if we want to fix the current build failures, [this](https://github.com/actions/setup-node#caching-global-packages-data) might be helpful?

**Comment by jc-tung** [comment]
> Also, if we want to fix the current build failures, [this](https://github.com/actions/setup-node#caching-global-packages-data) might be helpful?

Thanks for the suggestion! I did the formatting thing too.

**Review by nareha — APPROVED** [review]
lgtm, thanks for handling this setup!

**Comment by jc-tung** [comment]
FYI, I removed version 14.x from the yaml file b/c its incompatible with react-scripts test.

https://github.com/facebook/create-react-app/issues/11792

**Pull request merged**
